### ISSUE TITLE
no archive table is being created

### ISSUE THREAD

**Issue by ragrawal** [winton/acts_as_archive#49]
Hi,

I have created the config file but after running migration, no archive table is created. I am using Rails 3.2 and ruby 1.9 and latest version of acts_as_archive. Based on some previous issues, I also added acts_as_archive to my original table but that also didn't help. Am I missing any critical step ?

Ritesh

**Comment by ghost** [comment]
provide more information please if you can

**Comment by timscott** [comment]
I am also having this problem.  In my `Gemfile`:

``` ruby
gem 'acts_as_archive'
```

In `config/acts_as_archive.yml`:

``` yaml
Consumer:
  - class: Consumer::Cancelled
    table: cancelled_consumers
```

When I run `rake db:migrate` there is no output and no table is created.
